// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaOdontologica.API.Migrations
{
    [DbContext(typeof(ClinicaOdontologicaAPIContext))]
    [Migration("20260925020831_V01")]
    partial class V01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Cita", b =>
                {
                    b.Property<int>("idCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCita"));

                    b.Property<int>("IdOdontologo")
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("estadoCita")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_cita");

                    b.Property<DateTime>("fechaCita")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cita");

                    b.Property<int>("idConsultorio")
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.HasKey("idCita");

                    b.HasIndex("IdOdontologo");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("idConsultorio");

                    b.ToTable("citas");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Consultorio", b =>
                {
                    b.Property<int>("idConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idConsultorio"));

                    b.Property<string>("equipamientoPrincipal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipamiento_principal");

                    b.Property<string>("numeroSala")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_sala");

                    b.Property<int>("piso")
                        .HasColumnType("integer")
                        .HasColumnName("piso");

                    b.HasKey("idConsultorio");

                    b.ToTable("consultorios");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.DetalleCita", b =>
                {
                    b.Property<int>("idDetalleCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDetalleCita"));

                    b.Property<decimal>("CostoAplicado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_aplicado");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<int>("idTratamiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    b.Property<string>("observacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observaciones");

                    b.HasKey("idDetalleCita");

                    b.HasIndex("IdCita");

                    b.HasIndex("idTratamiento");

                    b.ToTable("detallescita");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Factura", b =>
                {
                    b.Property<int>("idFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idFactura"));

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<string>("estadoPado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<decimal>("impuestos")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("idFactura");

                    b.HasIndex("IdCita");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.HistorialMedico", b =>
                {
                    b.Property<int>("idHistorialMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_historial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idHistorialMedico"));

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("alergia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alergias");

                    b.Property<string>("enfermedadesPrevias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("enfermedades_previas");

                    b.Property<string>("tipoSangre")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("tipo_sangre");

                    b.HasKey("idHistorialMedico");

                    b.HasIndex("IdPaciente");

                    b.ToTable("historialesmedicos");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Odontologo", b =>
                {
                    b.Property<int>("idOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idOdontologo"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("idEspecialidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("registroMedico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registro_medico");

                    b.HasKey("idOdontologo");

                    b.ToTable("odontologos");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Paciente", b =>
                {
                    b.Property<int>("idPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPaciente"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateOnly>("fechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("idPaciente");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Receta", b =>
                {
                    b.Property<int>("idReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_receta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idReceta"));

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<string>("indicaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("indicaciones");

                    b.HasKey("idReceta");

                    b.HasIndex("IdCita");

                    b.ToTable("recetas");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Tratamiento", b =>
                {
                    b.Property<int>("idTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTratamiento"));

                    b.Property<decimal>("costoBase")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_base");

                    b.Property<TimeOnly>("duracionEstimadaMinutos")
                        .HasColumnType("time without time zone")
                        .HasColumnName("duracion_estimada_minutos");

                    b.Property<string>("nombreTratamiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_tratamiento");

                    b.HasKey("idTratamiento");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Cita", b =>
                {
                    b.HasOne("ClinicaOdontoligica.Modelos.Odontologo", "Odontologo")
                        .WithMany("Citas")
                        .HasForeignKey("IdOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontoligica.Modelos.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontoligica.Modelos.Consultorio", "Consultorio")
                        .WithMany()
                        .HasForeignKey("idConsultorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.DetalleCita", b =>
                {
                    b.HasOne("ClinicaOdontoligica.Modelos.Cita", "Cita")
                        .WithMany("DetallesCita")
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontoligica.Modelos.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("idTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Factura", b =>
                {
                    b.HasOne("ClinicaOdontoligica.Modelos.Cita", "Cita")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.HistorialMedico", b =>
                {
                    b.HasOne("ClinicaOdontoligica.Modelos.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Receta", b =>
                {
                    b.HasOne("ClinicaOdontoligica.Modelos.Cita", "Cita")
                        .WithMany("Recetas")
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Cita", b =>
                {
                    b.Navigation("DetallesCita");

                    b.Navigation("Facturas");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Odontologo", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("ClinicaOdontoligica.Modelos.Paciente", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
